language: php
php:
  - '5.6'
  - '7.0'
before_install:
  - sudo pip install cpp-coveralls
  - mongo --version
before_script:
  - chmod a+x travis-scripts/mongo-ext.sh
  - travis-scripts/mongo-ext.sh
  - composer self-update
  - composer install
  - mongod --dbpath=data/db &
  - sleep 3
script: phpunit --configuration phpunit.xml

